config/routes.rb
Rails.application.routes.draw do
  resources :user_neighborhoods

  resources :categories

  resources :neighborhoods

  devise_for :users
  resources :users

  root 'events#index'
  
  get '/preferences' => 'events#preferences'

end

app/models/event.rb
class Event < ActiveRecord::Base
attr_accessor :event_names, :parsed_response, :response, :user_neighborhoods, :user_categories

require 'rest_client'



  def initialize(user_neighborhoods, user_categories)
    @user_neighborhoods = user_neighborhoods
    @user_categories = user_categories
    @event_selection = 0
    @hood_select = 0
    @category_select = rand(0..user_categories.count)

    response = RestClient.get 'http://www.kimonolabs.com/api/bo0xm0eg?apikey=605ac5df894ed1e51bc760ce3f0daa17'
    @parsed_response = JSON.parse(response)['results']['collection1'].delete_if{ |i| i["description"] == "" || i["description"].length < 50 || i["description"].is_a?(Hash)}
    
    @category_results = []
    user_categories.pluck(:name).each do |cat|
       @category_results << @parsed_response.select { |i| i["category"] == cat}
    end

    @result = []
    user_neighborhoods.pluck(:name).each do |hood|
       @result << @category_results.flatten.select { |i| i["neighborhood"] == hood}
    end
    @result.flatten!

    while @result.empty?
      @hood_select += 1
      if @hood_select <= user_neighborhoods.count
        @result = @parsed_response.select { |i| i["neighborhood"] == user_neighborhoods.pluck(:name)[@hood_select]} #&& i["category"] == user_categories.pluck(:name)[@category_select]}
      elsif @hood_select > user_neighborhoods.count
            @result = @parsed_response.select { |i| i["neighborhood"] == "Midtown West"}
          end
        end
      end

  def event_name
     @result.map {|thing| thing["event_name"]}[@event_selection]
  end

  def description
    @result.map {|thing| thing["description"]}[@event_selection]
  end

  def url
    @result.map {|thing| thing["website"]["href"]}[@event_selection]
  end

  def pic
    @result.map {|thing| thing["pic"]["src"]}[@event_selection]
  end

  def neighborhood
    @result.map {|thing| thing["neighborhood"]}[@event_selection]
  end

  def category
    @result.map {|i| i["category"]}[@event_selection]
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :user_neighborhoods, :dependent=>:destroy
  has_many :neighborhoods, :through => :user_neighborhoods
  has_many :user_categories, :dependent=>:destroy
  has_many :categories, :through => :user_categories

 
  def self.trigger_daily_emails!
    self.all.each do |user|
    EventMailer.event_email(user).deliver
    end
  end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @event = Event.new(current_user.neighborhoods, current_user.categories)
  end

  def preferences
    @user = current_user
    @neighborhoods = Neighborhood.all
    @categories = Category.all
  end

end

app/helpers/events_helper.rb
module EventsHelper 

  def queens
    ['Long Island City', 'Astoria']
  end

  def manhattan
    ["East Village", "West Village", "Lower East Side", "Chinatown", "Soho", "Greenwich Village", "Gramercy & Flatiron", "Meatpacking District", "Tribeca", "Chelsea", "Financial District", "Midtown East", "Midtown West", "Upper East Side", "Upper West Side", "Harlem"]
  end

  def brooklyn
     ["Dumbo", 'Williamsburg', 'Greenpoint', 'Bushwick', 'Prospect Heights', 'Fort Greene', 'Gowanus', 'Park Slope', 'Prospect Park', 'Brooklyn Heights', 'Boerum Hill', 'Red Hook'] 
  end

end

app/views/events/index.html.erb
<div align = 'right' color="red"><button type="button" class="btn btn-primary btn-lg"><%= link_to "Update Preferences", preferences_path %></button></div>

<br/>
<br/>
<div id = "mainevent">

<center><em><h1><%= @event.event_name %></h1></em>
<h4><p>Neighborhood:<%= @event.neighborhood %><br/> Category:<%= @event.category %></p></h4>
</center>
<br/>
<p><%= @event.description %></p>
<br/>
<center><a href="<%= @event.url %>" target="_blank">Click for More Information</a></center>
<br/>
<br/>

<br/>
<center><img src="<%= @event.pic %>" class="img-responsive img-circle"/></br></center>
</div>
<br/>

app/views/events/preferences.html.erb
<br/>

<br/>
<div id = "mainevent">
<%= form_for(@user) do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %><br/>
 
   <h3>Select Neighborhood Preferences:</h3>

<font size="3">

<% queens %>
<% manhattan %>

<font color = "red">Queens </font>|
<font color = "black"> Brooklyn </font> |
<font color = "blue">Manhattan</font>
<br/>
<br/>

  <%= f.collection_check_boxes(:neighborhood_ids, @neighborhoods, :id, :name) do |cb|%>

    <% case %>
    <% when queens.include?(cb.text) %>
    <font color = "red"> <%= cb.check_box %><%= cb.label %></font>

    <% when brooklyn.include?(cb.text) %>
      <font color = "black"><%= cb.check_box %><%= cb.label %></font>

    <% when manhattan.include?(cb.text) %>
      <font color = "blue"><%= cb.check_box %><%= cb.label %></font>

    <% end %>

    <% end %>

</font>

  <h3>Select Your Interests:</h3>

<font size="3"> 
  <%= f.collection_check_boxes(:category_ids, @categories, :id, :name) do |cb| %>
      <%=cb.check_box%><%= cb.label %> |
    <%end%> </font> <br/>

    <%= f.submit 'Save'%>

    <% end %>

</div>
<%= link_to "Home", root_path %>